# Generated by Django 2.2.28 on 2024-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tapic',
            new_name='Topic',
        ),
    ]
